### ISSUE TITLE
how to navigate to output cell and copy the error?

### ISSUE THREAD

**Issue by Shahin-rmz** [jupyterlab-contrib/jupyterlab-vim#37] opened 2021-05-29 14:16 UTC
regularly, in my Vim (Spacevim) I used to navigate to the second window to copy the error and paste it. is there any ways now?
Thanks

**Comment by firai** [comment] 2023-10-01 04:18
Hi @Shahin-rmz, is this a duplicate of/superseded by your proposal in #56? If so, should we close this in favor of #56?

**Comment by Shahin-rmz** [comment] 2023-10-01 05:53
Hi, sure!
:)

**Closed** 2023-10-01 08:06 UTC
