### ISSUE TITLE
MacOS: vimbindings not working as expected

### ISSUE THREAD

**Issue by cvazz** [jupyterlab-contrib/jupyterlab-vim#143] opened 2024-07-04 09:09 UTC
## Description

Several commands that interact with jupyter, do not seem to be transmitted. Without having a custom keyboard settings file, commands in normal mode such as ctrl+o o or ctrl+k interact with the text as if I was in insert mode. So ctrl+o o just leads to a new line and ctrl+k deletes text. 

## Reproduce

With an empty keyboard settings file, on either Safari or Chrome: For example, press ctrl+k in command mode in a line with text.
The text gets deleted, the cursor remains in the same line.

## Expected behavior
In that example, I would expect the cursor would jump to the cell above

## Context

I am using version jupyterlab_vim 4.1.3, jupyterlab 4.2.1 and MacOS.

**Comment by firai** [comment] 2024-07-05 17:19
Thanks for reporting. This seems to be a duplicate of #138, and we plan to track updates there. Please provide more specific information or file a new issue if you think that you're experiencing a different issue than #138.

**Closed by firai** 2024-07-05 17:19 UTC
Labels: bug
