### ISSUE TITLE
I want to use ijkl to move cursor instad of hjkl ,how set ?

### ISSUE THREAD

**Issue by woodgreat** [jupyterlab-contrib/jupyterlab-vim#141] opened 2024-07-02 03:34 UTC
the original Vim hjkl is unhumanity ,so I want to use ijkl to move cursor instad of hjkl ,how set ? 
thank you

**Comment by firai** [comment] 2024-07-04 13:11
Thanks for reporting. I assume that you're referring to remapping these keys in notebooks, which is currently not possible because `j` and `k` are currently hardcoded for notebooks, and the issue is a duplicate of https://github.com/jupyterlab-contrib/jupyterlab-vim/issues/7. Additional context for the limitation is provided in https://github.com/jupyterlab-contrib/jupyterlab-vim/issues/113#issuecomment-1741095802. Contributions to add this capability would be welcome.

Remapping these keys in file editors should already be possible.

Closing in favor of https://github.com/jupyterlab-contrib/jupyterlab-vim/issues/7. Further discussions about this general issue can be continued there.

**Closed by firai** 2024-07-04 13:11 UTC
Labels: enhancement

**Comment by woodgreat** [comment] 2024-07-04 16:05
thanks for read. when we can fix the need?

**Comment by firai** [comment] 2024-07-05 17:29
Unfortunately, there isn't a specific timeline. This project is completely driven by PR contributions from volunteers. You are welcome to submit a PR.

**Comment by woodgreat** [comment] 2024-07-06 02:07
thanks
