### ISSUE TITLE
keep the current cell position fixed when saving with command "w"

### ISSUE THREAD

**Issue by wxie2013** [jupyterlab-contrib/jupyterlab-vim#151] opened 2024-11-12 16:00 UTC
When the contents of a cell exceed one page and are saved using the "w" command, the window shifts to the end of the cell where the "w" command was executed. This forces you to scroll back to the previous lines to continue editing. Is there a way to prevent the window from changing pages when executing the "w" command?

**Comment by firai** [comment] 2024-11-12 16:04
This seems to be a duplicate of #144

**Closed** 2024-11-12 16:26 UTC
Labels: duplicate, enhancement
