### ISSUE TITLE
Compatibility with jupyter-lab v4.0.2

### ISSUE THREAD

**Issue by dataselfservice** [jupyterlab-contrib/jupyterlab-vim#84] opened 2023-07-25 09:48 UTC
Hi,

does this work with v4.0.2?

Following `install.md`:
```
❯ pip install jupyterlab_vim  
Defaulting to user installation because normal site-packages is not writeable
Collecting jupyterlab_vim
  Using cached jupyterlab_vim-0.16.0-py3-none-any.whl (26 kB)
Installing collected packages: jupyterlab_vim
Successfully installed jupyterlab_vim-0.16.0

~ took 3s 
❯ jupyter labextension list 
JupyterLab v4.0.2
/home/a/.local/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.8 enabled OK (python, jupyterlab_widgets)
        @axlair/jupyterlab_vim v0.16.0 enabled  X (python, jupyterlab_vim)


   The following extensions are outdated:
        jupyterlab_pygments
        @axlair/jupyterlab_vim
        
   Consider running "jupyter labextension update --all" to check for updates.


~ took 2s 
❯ jupyter labextension update --all
(Deprecated) Updating extensions with the jupyter labextension update command is now deprecated and will be removed in a future major version of JupyterLab.

Users should manage prebuilt extensions with package managers like pip and conda, and extension authors are encouraged to distribute their extensions as prebuilt packages 

~ took 2s 
❯ 
```

**Comment by zndr27** [comment] 2023-07-27 15:49
Also having an issue with jupyter-lab v4

**Comment by lukashergt** [comment] 2023-07-27 17:20
See discussion in issue #68. Has been around for a while, currently no solution.

**Comment by krassowski** [comment] 2023-07-29 22:36
Closing as duplicate of #68. This is a work in progress, a PR will be up tomorrow.

**Closed by krassowski** 2023-07-29 22:36 UTC
Labels: bug
